// 
// Decompiled by Procyon v0.6.0
// 

package hazem.nurmontage.videoquran.constant;

public enum EntityAction
{
    ADD("ADD", 3), 
    ALINGMENT_STYLE("ALINGMENT_STYLE", 36), 
    ANIMATION("ANIMATION", 40), 
    BG_TEXT("BG_TEXT", 16), 
    BOLD_STYLE("BOLD_STYLE", 32), 
    COLOR_OUTLINE_IMG("COLOR_OUTLINE_IMG", 13), 
    COLOR_OUTLINE_TEXT("COLOR_OUTLINE_TEXT", 8), 
    COLOR_TACHKIL("COLOR_TACHKIL", 15), 
    COLOR_TEXT("COLOR_TEXT", 10), 
    DELETE("DELETE", 19), 
    DELETE_MULTIPLE("DELETE_MULTIPLE", 20), 
    FONT_TEXT("FONT_TEXT", 28), 
    GLOW_SHADOW("GLOW_SHADOW", 30), 
    ICON_QURAN("ICON_QURAN", 31), 
    ITALIC_STYLE("ITALIC_STYLE", 34), 
    LAYER("LAYER", 7), 
    MOTION_AND_TIME_VIEW("MOTION_AND_TIME_VIEW", 39), 
    MOTION_VIEW("MOTION_VIEW", 38), 
    MOVE("MOVE", 2), 
    OPACITY_IMAGE("OPACITY_IMAGE", 17), 
    OPACITY_TEXT("OPACITY_TEXT", 18), 
    ROTATE("ROTATE", 4), 
    ROUND_IMAGE("ROUND_IMAGE", 12), 
    SHADOW_IMAGE("SHADOW_IMAGE", 11), 
    SHADOW_TEXT("SHADOW_TEXT", 21), 
    SIZE_OUTLINE_IMG("SIZE_OUTLINE_IMG", 14), 
    SIZE_OUTLINE_TEXT("SIZE_OUTLINE_TEXT", 9), 
    SPLIT("SPLIT", 0), 
    STRIKE_LINE_STYLE("STRIKE_LINE_STYLE", 33), 
    TEXT_SIZE("TEXT_SIZE", 29), 
    TIME_LINE_VIEW("TIME_LINE_VIEW", 37), 
    TO_BACK("TO_BACK", 5), 
    TO_FRONT("TO_FRONT", 6), 
    TO_HORIZONTAL_CENTER("TO_HORIZONTAL_CENTER", 24), 
    TO_HORIZONTAL_LEFT("TO_HORIZONTAL_LEFT", 23), 
    TO_HORIZONTAL_RIGHT("TO_HORIZONTAL_RIGHT", 22), 
    TO_VERTICAL_BOTTOM("TO_VERTICAL_BOTTOM", 27), 
    TO_VERTICAL_CENTER("TO_VERTICAL_CENTER", 25), 
    TO_VERTICAL_TOP("TO_VERTICAL_TOP", 26), 
    TRIM("TRIM", 1), 
    UNDERLINE_STYLE("UNDERLINE_STYLE", 35);
    
    private EntityAction(final String name, final int ordinal) {
    }
}
