/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  android.content.Context
 *  android.graphics.Canvas
 *  android.graphics.Color
 *  android.graphics.Paint
 *  android.graphics.Paint$Align
 *  android.graphics.Paint$Style
 *  android.graphics.Path
 *  android.graphics.RectF
 *  android.graphics.Typeface
 *  android.util.AttributeSet
 *  android.view.View
 */
package hazem.nurmontage.videoquran.views;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.Path;
import android.graphics.RectF;
import android.graphics.Typeface;
import android.util.AttributeSet;
import android.view.View;

public class NeumorphicView
extends View {
    private int accentColor;
    private int baseColor;
    private int darkShadowColor;
    private int iconColor;
    private int lightHighlightColor;
    private Paint paint;
    private RectF rectF;
    private int textColor;

    public NeumorphicView(Context context) {
        super(context);
        this.init();
    }

    public NeumorphicView(Context context, AttributeSet attributeSet) {
        super(context, attributeSet);
        this.init();
    }

    public NeumorphicView(Context context, AttributeSet attributeSet, int n) {
        super(context, attributeSet, n);
        this.init();
    }

    private Path createTrianglePath(float f, float f2, float f3, boolean bl) {
        Path path = new Path();
        float f4 = 2.0f;
        if (bl) {
            float f5 = f + (f3 /= f4);
            f4 = f2 - f3;
            path.moveTo(f5, f4);
            path.lineTo(f -= f3, f2);
            path.lineTo(f5, f2 += f3);
        } else {
            float f6 = f - (f3 /= f4);
            f4 = f2 - f3;
            path.moveTo(f6, f4);
            path.lineTo(f += f3, f2);
            path.lineTo(f6, f2 += f3);
        }
        path.close();
        return path;
    }

    private float dpToPx(float f) {
        float f2 = this.getResources().getDisplayMetrics().density;
        return f * f2;
    }

    private void drawNeumorphicCircle(Canvas canvas, float f, float f2, float f3, int n, int n2, int n3, float f4, boolean bl) {
        Paint paint = this.paint;
        int n4 = bl ? n2 : n3;
        paint.setColor(n4);
        float f5 = f + f4;
        float f6 = f2 + f4;
        Paint paint2 = this.paint;
        canvas.drawCircle(f5, f6, f3, paint2);
        paint = this.paint;
        if (bl) {
            n2 = n3;
        }
        paint.setColor(n2);
        float f7 = f - f4;
        float f8 = f2 - f4;
        Paint paint3 = this.paint;
        canvas.drawCircle(f7, f8, f3, paint3);
        this.paint.setColor(n);
        Paint paint4 = this.paint;
        canvas.drawCircle(f, f2, f3, paint4);
    }

    private void drawNeumorphicRect(Canvas canvas, float f, float f2, float f3, float f4, float f5, int n, int n2, int n3, float f6, boolean bl) {
        NeumorphicView neumorphicView = this;
        float f7 = f;
        float f8 = f2;
        float f9 = f5;
        Paint paint = this.paint;
        int n4 = bl ? n2 : n3;
        paint.setColor(n4);
        paint = neumorphicView.rectF;
        float f10 = f7 + f6;
        float f11 = f8 + f6;
        float f12 = f7 + f3;
        float f13 = f12 + f6;
        float f14 = f8 + f4;
        float f15 = f14 + f6;
        paint.set(f10, f11, f13, f15);
        paint = neumorphicView.rectF;
        Paint paint2 = neumorphicView.paint;
        canvas.drawRoundRect((RectF)paint, f9, f9, paint2);
        paint = neumorphicView.paint;
        n4 = bl ? n3 : n2;
        paint.setColor(n4);
        paint = neumorphicView.rectF;
        f10 = f7 - f6;
        f11 = f8 - f6;
        f13 = f12 - f6;
        f15 = f14 - f6;
        paint.set(f10, f11, f13, f15);
        paint = neumorphicView.rectF;
        paint2 = neumorphicView.paint;
        canvas.drawRoundRect((RectF)paint, f9, f9, paint2);
        paint = neumorphicView.paint;
        n4 = n;
        paint.setColor(n);
        neumorphicView.rectF.set(f, f2, f12, f14);
        RectF rectF = neumorphicView.rectF;
        Paint paint3 = neumorphicView.paint;
        canvas.drawRoundRect(rectF, f9, f9, paint3);
    }

    private void init() {
        Paint paint;
        this.paint = paint = new Paint(1);
        Paint.Style style2 = Paint.Style.FILL;
        paint.setStyle(style2);
        paint = new RectF();
        this.rectF = paint;
        int n = 200;
        n = Color.rgb((int)n, (int)n, (int)n);
        this.setBaseThemeColor(n);
    }

    protected void onDraw(Canvas canvas) {
        super.onDraw(canvas);
        float f = 30.0f;
        int n = (int)this.dpToPx(f);
        int n2 = this.getWidth();
        int n3 = n * 2;
        float f2 = n2 - n3;
        float f3 = this.getHeight() - n3;
        float f4 = n;
        float f5 = this.dpToPx(f);
        int n4 = this.baseColor;
        int n5 = this.darkShadowColor;
        int n6 = this.lightHighlightColor;
        float f6 = 10.0f;
        float f7 = this.dpToPx(f6);
        NeumorphicView neumorphicView = this;
        Object object = canvas;
        float f8 = f4;
        float f9 = f4;
        f = f6;
        f6 = f2;
        float f10 = f4;
        f4 = f7;
        f7 = f2;
        boolean bl = true;
        f2 = Float.MIN_VALUE;
        this.drawNeumorphicRect(canvas, f8, f8, f6, f3, f5, n4, n5, n6, f4, bl);
        float f11 = 100.0f;
        f4 = this.dpToPx(f11);
        float f12 = this.getWidth();
        float f13 = 2.0f;
        f2 = f12 / f13;
        f11 = this.dpToPx(f11);
        float f14 = f8 + f11;
        int n7 = this.baseColor;
        int n8 = this.lightHighlightColor;
        n4 = this.darkShadowColor;
        float f15 = this.dpToPx(f);
        f8 = f2;
        f9 = f14;
        f6 = f4;
        this.drawNeumorphicCircle(canvas, f2, f14, f4, n7, n8, n4, f15, false);
        neumorphicView = this.paint;
        n3 = this.textColor;
        neumorphicView.setColor(n3);
        neumorphicView = this.paint;
        f8 = this.dpToPx(30.0f);
        neumorphicView.setTextSize(f8);
        neumorphicView = this.paint;
        object = Typeface.create((String)"sans-serif-medium", (int)1);
        neumorphicView.setTypeface((Typeface)object);
        neumorphicView = this.paint;
        object = Paint.Align.CENTER;
        neumorphicView.setTextAlign((Paint.Align)object);
        f11 = this.paint.getTextSize() / 3.0f;
        f11 = f14 + f11;
        object = this.paint;
        canvas.drawText("\u0627\u0644\u0643\u064e\u0647\u0652\u0641", f2, f11, (Paint)object);
        neumorphicView = this.paint;
        f2 = 20.0f;
        f12 = this.dpToPx(f2);
        neumorphicView.setTextSize(f12);
        neumorphicView = this.paint;
        String string2 = "sans-serif-light";
        object = Typeface.create((String)string2, (int)0);
        neumorphicView.setTypeface((Typeface)object);
        f11 = (float)this.getWidth() / f13;
        f14 += f4;
        f4 = 40.0f;
        f12 = this.dpToPx(f4);
        f12 = f14 + f12;
        Paint paint = this.paint;
        canvas.drawText("Al- Kahfi", f11, f12, paint);
        neumorphicView = this.paint;
        f12 = this.dpToPx(16.0f);
        neumorphicView.setTextSize(f12);
        f11 = (float)this.getWidth() / f13;
        f12 = this.dpToPx(65.0f);
        f12 = f14 + f12;
        paint = this.paint;
        canvas.drawText("Ustadz : Muzammil Hasballah", f11, f12, paint);
        f11 = this.dpToPx(60.0f);
        f3 = f7 - f11;
        f7 = this.dpToPx(f2);
        f12 = this.dpToPx(30.0f);
        f6 = f10 + f12;
        f11 = this.dpToPx(115.0f);
        f9 = f14 + f11;
        f8 = this.dpToPx(f);
        n3 = this.baseColor;
        n2 = this.darkShadowColor;
        n6 = this.lightHighlightColor;
        float f16 = this.dpToPx(5.0f);
        neumorphicView = this;
        object = canvas;
        float f17 = f8;
        f8 = f6;
        float f18 = f9;
        f = f6;
        f6 = f3;
        f3 = f7;
        f5 = f17;
        n4 = n3;
        n5 = n2;
        int n9 = n;
        n = 0x42200000;
        float f19 = f4;
        f4 = f16;
        n = 1101004800;
        f19 = f2;
        bl = true;
        f2 = Float.MIN_VALUE;
        this.drawNeumorphicRect(canvas, f8, f9, f6, f7, f17, n3, n2, n6, f16, bl);
        f2 = f6;
        f11 = (float)((double)f6 * 0.6);
        object = this.paint;
        int n10 = this.accentColor;
        object.setColor(n10);
        object = this.rectF;
        f6 = f8 + f11;
        f11 = f9;
        object.set(f8, f18, f6, f9 += f7);
        object = this.rectF;
        paint = this.paint;
        f9 = f17;
        canvas.drawRoundRect((RectF)object, f17, f17, paint);
        f = this.dpToPx(60.0f);
        f7 = this.dpToPx(f19);
        f12 = this.dpToPx(70.0f);
        float f20 = f18 + f12;
        float f21 = this.dpToPx(f19);
        f11 = (float)this.getWidth() / f13 - f - f21;
        f8 = this.dpToPx(40.0f);
        float f22 = f11 - f8;
        n4 = this.baseColor;
        n5 = this.darkShadowColor;
        n6 = this.lightHighlightColor;
        f4 = this.dpToPx(8.0f);
        object = canvas;
        f8 = f22;
        f9 = f20;
        f6 = f;
        f3 = f;
        f5 = f7;
        bl = true;
        f2 = Float.MIN_VALUE;
        this.drawNeumorphicRect(canvas, f22, f20, f, f, f7, n4, n5, n6, f4, bl);
        neumorphicView = this.paint;
        n3 = this.iconColor;
        neumorphicView.setColor(n3);
        f11 = this.dpToPx(f19);
        f12 = f22 + f11;
        f11 = this.dpToPx(f19);
        f8 = f20 + f11;
        f2 = 25.0f;
        f11 = this.dpToPx(f2);
        f9 = f22 + f11;
        f6 = this.dpToPx(40.0f);
        f6 = f20 + f6;
        Paint paint2 = this.paint;
        neumorphicView = canvas;
        canvas.drawRect(f12, f8, f9, f6, paint2);
        f11 = this.dpToPx(f2);
        f11 = f22 + f11;
        f8 = this.dpToPx(30.0f);
        f8 = f20 + f8;
        f12 = this.dpToPx(f19);
        neumorphicView = this.createTrianglePath(f11, f8, f12, true);
        object = this.paint;
        canvas.drawPath((Path)neumorphicView, (Paint)object);
        f11 = (float)this.getWidth() / f13;
        f12 = f / f13;
        f22 = f11 - f12;
        n4 = this.baseColor;
        n5 = this.darkShadowColor;
        n6 = this.lightHighlightColor;
        f17 = this.dpToPx(8.0f);
        neumorphicView = this;
        object = canvas;
        f8 = f22;
        f9 = f20;
        f6 = f;
        f4 = f17;
        bl = true;
        f2 = Float.MIN_VALUE;
        this.drawNeumorphicRect(canvas, f22, f20, f, f, f7, n4, n5, n6, f17, bl);
        neumorphicView = this.paint;
        n3 = this.iconColor;
        neumorphicView.setColor(n3);
        f11 = this.dpToPx(f19);
        f12 = f22 + f11;
        f11 = this.dpToPx(f19);
        f8 = f20 + f11;
        f9 = this.dpToPx(30.0f);
        f9 = f22 + f9;
        f6 = this.dpToPx(40.0f);
        f6 = f20 + f6;
        paint2 = this.paint;
        neumorphicView = canvas;
        canvas.drawRect(f12, f8, f9, f6, paint2);
        f11 = this.dpToPx(35.0f);
        f12 = f22 + f11;
        f11 = this.dpToPx(f19);
        f8 = f20 + f11;
        f4 = 45.0f;
        f11 = this.dpToPx(f4);
        f9 = f22 + f11;
        f6 = this.dpToPx(40.0f);
        f6 = f20 + f6;
        paint2 = this.paint;
        canvas.drawRect(f12, f8, f9, f6, paint2);
        f11 = (float)this.getWidth() / f13 + f21;
        f8 = this.dpToPx(40.0f);
        f21 = f11 + f8;
        n4 = this.baseColor;
        n5 = this.darkShadowColor;
        n6 = this.lightHighlightColor;
        f22 = this.dpToPx(8.0f);
        neumorphicView = this;
        f8 = f21;
        f9 = f20;
        f6 = f;
        f = f4;
        f4 = f22;
        bl = true;
        f2 = Float.MIN_VALUE;
        this.drawNeumorphicRect(canvas, f21, f20, f6, f6, f7, n4, n5, n6, f22, bl);
        neumorphicView = this.paint;
        n3 = this.iconColor;
        neumorphicView.setColor(n3);
        f11 = 40.0f;
        f12 = this.dpToPx(f11);
        f12 = f21 + f12;
        f8 = this.dpToPx(f19);
        f8 = f20 + f8;
        f9 = this.dpToPx(f);
        f9 = f21 + f9;
        f6 = this.dpToPx(f11);
        f6 = f20 + f6;
        paint2 = this.paint;
        neumorphicView = canvas;
        canvas.drawRect(f12, f8, f9, f6, paint2);
        f11 = this.dpToPx(35.0f);
        f11 = f21 + f11;
        f12 = this.dpToPx(30.0f);
        f12 = f20 + f12;
        f8 = this.dpToPx(f19);
        neumorphicView = this.createTrianglePath(f11, f12, f8, false);
        object = this.paint;
        canvas.drawPath((Path)neumorphicView, (Paint)object);
        neumorphicView = this.paint;
        f12 = this.dpToPx(12.0f);
        neumorphicView.setTextSize(f12);
        neumorphicView = this.paint;
        object = string2;
        object = Typeface.create((String)string2, (int)0);
        neumorphicView.setTypeface((Typeface)object);
        neumorphicView = this.paint;
        String string3 = "Created by : story_rilla";
        f11 = neumorphicView.measureText(string3);
        f4 = (float)this.getWidth() / f13;
        f12 = this.getHeight() - n9;
        f8 = this.dpToPx(f19);
        f7 = f12 - f8;
        f12 = 40.0f;
        f8 = this.dpToPx(f12);
        f6 = f11 + f8;
        f3 = this.dpToPx(f12);
        f11 = (float)this.getWidth() / f13;
        f12 = f6 / f13;
        f8 = f11 - f12;
        f9 = (float)(this.getHeight() - n9) - f3;
        float f23 = 15.0f;
        f5 = this.dpToPx(f23);
        n4 = this.baseColor;
        n5 = this.darkShadowColor;
        n3 = this.lightHighlightColor;
        f13 = this.dpToPx(5.0f);
        neumorphicView = this;
        n9 = n3;
        object = canvas;
        f = f23;
        n6 = n3;
        f = f4;
        f4 = f13;
        bl = true;
        f2 = Float.MIN_VALUE;
        this.drawNeumorphicRect(canvas, f8, f9, f6, f3, f5, n4, n5, n3, f13, bl);
        neumorphicView = this.paint;
        n3 = this.iconColor;
        neumorphicView.setColor(n3);
        f2 = 25.0f;
        f11 = this.dpToPx(f2);
        f11 = f7 + f11;
        object = this.paint;
        canvas.drawText(string3, f, f11, (Paint)object);
        f = this.dpToPx(40.0f);
        f19 = this.dpToPx(20.0f);
        f5 = this.dpToPx(15.0f);
        n4 = this.baseColor;
        n5 = this.darkShadowColor;
        n6 = this.lightHighlightColor;
        f4 = this.dpToPx(5.0f);
        neumorphicView = this;
        object = canvas;
        f8 = f19;
        f9 = f19;
        f6 = f;
        f3 = f;
        float f24 = f;
        f = f2;
        bl = true;
        f2 = Float.MIN_VALUE;
        this.drawNeumorphicRect(canvas, f19, f19, f6, f6, f5, n4, n5, n6, f4, bl);
        neumorphicView = this.paint;
        n3 = this.iconColor;
        neumorphicView.setColor(n3);
        neumorphicView = new Path();
        f12 = this.dpToPx(f) + f19;
        f8 = 15.0f;
        f9 = this.dpToPx(f8) + f19;
        neumorphicView.moveTo(f12, f9);
        f12 = this.dpToPx(f8) + f19;
        f8 = this.dpToPx(f) + f19;
        neumorphicView.lineTo(f12, f8);
        f12 = this.dpToPx(f) + f19;
        f9 = this.dpToPx(35.0f) + f19;
        neumorphicView.lineTo(f12, f9);
        neumorphicView.close();
        object = this.paint;
        canvas.drawPath((Path)neumorphicView, (Paint)object);
        f8 = (float)this.getWidth() - f19 - f6;
        f5 = this.dpToPx(15.0f);
        n4 = this.baseColor;
        n5 = this.darkShadowColor;
        n6 = this.lightHighlightColor;
        f4 = this.dpToPx(5.0f);
        bl = true;
        neumorphicView = this;
        object = canvas;
        f9 = f19;
        this.drawNeumorphicRect(canvas, f8, f19, f6, f6, f5, n4, n5, n6, f4, bl);
        neumorphicView = this.paint;
        n3 = this.iconColor;
        neumorphicView.setColor(n3);
        f11 = (float)this.getWidth() - f19 - f6;
        f12 = 20.0f;
        f8 = this.dpToPx(f12);
        f11 += f8;
        f8 = this.dpToPx(f12) + f19;
        f6 = this.dpToPx(5.0f);
        Paint paint3 = this.paint;
        canvas.drawCircle(f11, f8, f6, paint3);
        f11 = (float)this.getWidth() - f19 - f3;
        f8 = this.dpToPx(f12) + f11;
        f11 = this.dpToPx(f12);
        f9 = f19 + f11;
        f11 = (float)this.getWidth() - f19 - f3;
        f6 = this.dpToPx(35.0f) + f11;
        f12 = this.dpToPx(5.0f);
        f3 = f19 + f12;
        Paint paint4 = this.paint;
        neumorphicView = canvas;
        f12 = f8;
        f8 = f9;
        f9 = f6;
        f6 = f3;
        paint2 = paint4;
        canvas.drawLine(f12, f8, f9, f3, paint4);
        f11 = (float)this.getWidth() - f19 - f24;
        f12 = 20.0f;
        f8 = this.dpToPx(f12) + f11;
        f11 = this.dpToPx(f12);
        f9 = f19 + f11;
        f11 = (float)this.getWidth() - f19 - f24;
        f12 = 35.0f;
        f6 = this.dpToPx(f12) + f11;
        f11 = this.dpToPx(f12);
        f3 = f19 + f11;
        paint4 = this.paint;
        f12 = f8;
        f8 = f9;
        f9 = f6;
        f6 = f3;
        paint2 = paint4;
        canvas.drawLine(f12, f8, f9, f3, paint4);
        f = f19 + f24;
        f12 = this.dpToPx(10.0f);
        f8 = f + f12;
        f5 = this.dpToPx(15.0f);
        n4 = this.baseColor;
        n5 = this.darkShadowColor;
        n6 = this.lightHighlightColor;
        f4 = this.dpToPx(5.0f);
        neumorphicView = this;
        f9 = f19;
        f6 = f24;
        f3 = f24;
        this.drawNeumorphicRect(canvas, f8, f19, f24, f24, f5, n4, n5, n6, f4, bl);
        neumorphicView = this.paint;
        n3 = this.iconColor;
        neumorphicView.setColor(n3);
        f11 = 10.0f;
        f12 = this.dpToPx(f11) + f;
        f8 = this.dpToPx(15.0f);
        f12 += f8;
        f8 = this.dpToPx(f11) + f19;
        f9 = 20.0f;
        f6 = this.dpToPx(f9);
        f8 += f6;
        f6 = this.dpToPx(5.0f);
        paint2 = this.paint;
        canvas.drawCircle(f12, f8, f6, paint2);
        f12 = this.dpToPx(f11) + f;
        f8 = this.dpToPx(f9);
        f12 += f8;
        f8 = this.dpToPx(f11) + f19;
        f6 = this.dpToPx(f11);
        f8 += f6;
        f6 = this.dpToPx(f11) + f;
        f3 = this.dpToPx(f9);
        f6 += f3;
        f3 = this.dpToPx(f11) + f19;
        f11 = this.dpToPx(f9);
        paint4 = this.paint;
        neumorphicView = canvas;
        f9 = f6;
        f6 = f3 += f11;
        paint2 = paint4;
        canvas.drawLine(f12, f8, f9, f3, paint4);
        f11 = 10.0f;
        f12 = this.dpToPx(f11) + f;
        f8 = this.dpToPx(20.0f);
        f12 += f8;
        f8 = this.dpToPx(f11) + f19;
        f9 = this.dpToPx(f11);
        f8 += f9;
        f9 = this.dpToPx(f11);
        f += f9;
        f9 = this.dpToPx(35.0f) + f;
        f6 = this.dpToPx(f11);
        f19 += f6;
        f11 = this.dpToPx(f11);
        f6 = f19 + f11;
        paint2 = this.paint;
        canvas.drawLine(f12, f8, f9, f6, paint2);
    }

    public void setBaseThemeColor(int n) {
        this.baseColor = n;
        int n2 = Color.red((int)n);
        int n3 = Color.green((int)n);
        n = Color.blue((int)n);
        int n4 = n2 + -50;
        n4 = Math.max(0, n4);
        int n5 = n3 + -50;
        n5 = Math.max(0, n5);
        int n6 = n + -50;
        n6 = Math.max(0, n6);
        this.darkShadowColor = n4 = Color.argb((int)150, (int)n4, (int)n5, (int)n6);
        n4 = n2 + 50;
        n5 = 255;
        n4 = Math.min(n5, n4);
        n6 = n3 + 50;
        n6 = Math.min(n5, n6);
        int n7 = n + 50;
        n5 = Math.min(n5, n7);
        this.lightHighlightColor = n4 = Color.argb((int)200, (int)n4, (int)n6, (int)n5);
        n4 = n2 + -30;
        n4 = Math.max(0, n4);
        n5 = n3 + -30;
        n5 = Math.max(0, n5);
        n6 = n + -30;
        n6 = Math.max(0, n6);
        this.accentColor = n4 = Color.rgb((int)n4, (int)n5, (int)n6);
        n2 += -100;
        n2 = Math.max(0, n2);
        n3 += -100;
        n3 = Math.max(0, n3);
        n += -100;
        n = Math.max(0, n);
        this.textColor = n = Color.rgb((int)n2, (int)n3, (int)n);
        this.iconColor = n;
        n = this.baseColor;
        this.setBackgroundColor(n);
        this.invalidate();
    }
}

